# All symbols to subscribe — grouped by exchange segment
# OpenAlgo token format: exchange:symbol

NSE_INDEX = [
    'NIFTY', 'BANKNIFTY', 'MIDCPNIFTY', 'FINNIFTY',
]

BSE_INDEX = [
    'SENSEX', 'BANKEX',
]

MCX = [
    'CRUDEOIL', 'GOLD', 'GOLDM', 'SILVER', 'SILVERM',
    'NATURALGAS', 'COPPER', 'ZINC', 'NICKEL',
]

# NSE F&O stocks (active lot sizes as of 2024)
NSE_FNO = [
    'RELIANCE','TCS','HDFCBANK','INFY','ICICIBANK','SBIN','BAJFINANCE','HINDUNILVR',
    'ADANIENT','ADANIPORTS','AXISBANK','BHARTIARTL','WIPRO','LT','HCLTECH',
    'MARUTI','SUNPHARMA','TITAN','ULTRACEMCO','NTPC','ONGC','POWERGRID',
    'COALINDIA','TATAMOTORS','TATASTEEL','JSWSTEEL','HINDALCO','GRASIM',
    'BAJAJFINSV','BAJAJ-AUTO','HEROMOTOCO','EICHERMOT','M&M','APOLLOHOSP',
    'DRREDDY','CIPLA','DIVISLAB','BPCL','BRITANNIA','ITC','NESTLEIND',
    'ASIANPAINT','DMART','PIDILITIND','SIEMENS','HAVELLS','TRENT','ZOMATO',
    'PAYTM','NYKAA','POLICYBZR','DELHIVERY','CARTRADE','IRCTC','IRFC',
    'RVNL','RAILVIKAS','PNB','BANKBARODA','CANBK','FEDERALBNK','IDFCFIRSTB',
    'KOTAKBANK','INDUSINDBK','BANDHANBNK','AUBANK','RBLBANK',
    'HDFCLIFE','SBILIFE','ICICIPRULI','ICICIGI','SBICARD',
    'CHOLAFIN','MUTHOOTFIN','MANAPPURAM','SHRIRAMFIN','BAJAJHLDNG',
    'LTF','M&MFIN','RECLTD','PFC','IREDA',
    'TECHM','MPHASIS','LTIM','PERSISTENT','COFORGE','OFSS',
    'TATACONSUM','MCDOWELL-N','RADICO','UBL',
    'GODREJCP','DABUR','MARICO','COLPAL','PGHH',
    'ATUL','PIDILITIND','DEEPAKNTR','NAVINFLUOR',
    'UPL','PIIND','RALLIS','CHAMBAL',
    'VEDL','NMDC','SAIL','JINDALSTEL','NATIONALUM',
    'AMBUJACEM','ACC','RAMCOCEM','JKCEMENT',
    'DLF','GODREJPROP','OBEROIREAL','LODHA','PRESTIGE',
    'CONCOR','ADANIGREEN','TATAPOWER','TORNTPOWER','CESC','IEX',
    'INDIGO','SPICEJET','GMRINFRA','ASHOKLEY',
    'APOLLOTYRE','BALKRISIND','MRF','CEAT',
    'VOLTAS','BLUESTARCO','WHIRLPOOL','HAVELLS','CROMPTON',
    'BIOCON','ALKEM','LUPIN','AUROPHARMA','TORNTPHARM','GLENMARK',
    'JUBLFOOD','DEVYANI','WESTLIFE','SAPPHIRE',
    'ZEEL','SUNTV','PVRINOX',
    'NAUKRI','JUSTDIAL',
    'MFSL','NIACL','GICRE','STARHEALTH',
    'ABCAPITAL','IIFL','ANGELONE','MOTILALOFS','360ONE',
]

# Lot sizes per symbol
LOT_SIZES = {
    # Indices
    'NIFTY': 50, 'BANKNIFTY': 15, 'MIDCPNIFTY': 75, 'FINNIFTY': 40,
    'SENSEX': 10, 'BANKEX': 15,
    # MCX
    'CRUDEOIL': 100, 'GOLD': 100, 'GOLDM': 10,
    'SILVER': 30, 'SILVERM': 5, 'NATURALGAS': 1250,
    'COPPER': 2500, 'ZINC': 5000, 'NICKEL': 1500,
    # F&O stocks — default 1 lot = varies; common ones listed
    'RELIANCE': 250, 'TCS': 150, 'HDFCBANK': 550, 'INFY': 300,
    'ICICIBANK': 700, 'SBIN': 1500, 'BAJFINANCE': 125, 'HINDUNILVR': 300,
    'TATAMOTORS': 1425, 'TATASTEEL': 5500, 'JSWSTEEL': 600,
}

ALL_SYMBOLS = NSE_INDEX + BSE_INDEX + MCX + NSE_FNO

# Exchange mapping for OpenAlgo subscription
EXCHANGE_MAP = {sym: 'NSE_INDEX' for sym in NSE_INDEX}
EXCHANGE_MAP.update({sym: 'BSE_INDEX' for sym in BSE_INDEX})
EXCHANGE_MAP.update({sym: 'MCX' for sym in MCX})
EXCHANGE_MAP.update({sym: 'NSE' for sym in NSE_FNO})
